### ISSUE TITLE
Weather sounds last forever

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/WeatherRandomizer#1]
Weather sounds go non-stop even when flying and/or teleporting into space.

This is at least with one of the heavy sandstorms...not sure which. I dont see any commands to change the weather so can't test other ones.

**Comment by N1Ran** [comment]
!weather set planetName weatherSubTypeName

**Comment by Blaylock1988** [comment]
Thanks! snowlight and snowheavy doing have sound issues in space (they fade out when exiting the weather).

**Comment by N1Ran** [comment]
sounds like issues with the weather def itself.  Plugin can't change that, best to added bugged weathers to the exception list
