### ISSUE TITLE
Crash to desktop on respawn when dying in weather.

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/WeatherRandomizer#2]
Title explains it. Attempting to respawn anywhere causes immediate crash to desktop

**Comment by N1Ran** [comment]
going to need client log to troubleshoot this

**Comment by Blaylock1988** [comment]
[SpaceEngineers_20200508_222716346.log](https://github.com/N1Ran/WeatherRandomizer/files/4602517/SpaceEngineers_20200508_222716346.log)

```2020-05-08 22:30:39.450 - Thread:   1 ->  Exception occured: Sandbox.MyInitializer+MyOutOfMemoryException: Game is at critically low memory```

I have 16GB of RAM, and have never had memory issues with SE before. This crash is repeatable.

**Comment by N1Ran** [comment]
also, check VRAM.  Weather effects are highly intensive to graphics

**Comment by Blaylock1988** [comment]
I remember this was a crash that Keen fixed with the vanilla weathers a few weeks ago. Identical issue. I tested respawning with snowlight and snowheavy, and had no issues with crashing.

**Comment by N1Ran** [comment]
Plugin can't fix bugged game issues
