### ISSUE TITLE
Weather effects in space (sort of)

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/WeatherRandomizer#3]
This might be related to the sound of weather lasing forever. When going from weather area to space, I often see small puffs of dust storm effects even many thousands of kms away from the planet, and even in the respawn screen when looking at a spawn that is in space.

**Comment by N1Ran** [comment]
Can't reproduce this.  Need more data

**Comment by Blaylock1988** [comment]
After crashing a few times it seems to have stopped doing this. I think it might be a keen issue not terminating the effects properly for the client.

**Comment by Blaylock1988** [comment]
This can't be a vanilla problem...

I set the weather as clear on the planet. Another person logged in right after and had snow in deep space and didn't even visit the planet. he relogged and it magically switched to sandstorm in space.

![image](https://user-images.githubusercontent.com/62247634/81483897-6bdc8400-920f-11ea-833e-bbaff25f3de4.png)
![image](https://user-images.githubusercontent.com/62247634/81483901-7008a180-920f-11ea-9e78-665cfaede510.png)
![image](https://user-images.githubusercontent.com/62247634/81483903-76971900-920f-11ea-948f-b49c79b5d5f1.png)

**Comment by N1Ran** [comment]
Are those modded planets?

**Comment by Blaylock1988** [comment]
all of the screenshots are in space (asteroid looks a bit like planet mountain). There is a modded planet (Bylen) which I added to the exception. Weather is only set to spawn on vanilla mars.
