### ISSUE TITLE
Vanilla weather commands do not function.

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/WeatherRandomizer#7]
As title states, although maybe its intentional or overridden by the plugin commands?

Tested with admin and creative (and all other admin options) checked

**Comment by N1Ran** [comment]
Fake news.  Plugin won't affect vanilla functions.  Just adds an extra layer.
Make sure you're using the following format. `/weather weatherSubtypName`

**Comment by Blaylock1988** [comment]
Yeah I was using the correct format. I added and removed the static weather in our world just fine prior to installing the plugin with the vanilla commands.

**Comment by N1Ran** [comment]
which weather are you trying to add cause vanilla command only allows `Clear`, `FogLight`,`FogHeavy`,`SnowLight`, and `SnowHeavy`.  The plugin can spawn the others that vanilla command can't.  Your character also needs to be on a planet for the vanilla command to work
